### ISSUE TITLE
Disabled Click of Child Elements when in 'PAN' mode

### ISSUE THREAD

**Issue by swizzmagik** [KensingtonTech/ng2-panzoom#12]
When utilizing this feature on a grid of clickable elements (in my case `<a>` tags), the 'mouseUp' event to release the panning feature triggers the click of the child element. It would be great if there was a way to prevent the propagation of this event to child elements when 'pan' mode is enabled.

**Comment by KensingtonTech** [comment]
I encountered something similar in my own application, but the inherent problem was that I sometimes wanted the click to occur, such as when I clicked a child element, and sometimes I didn't, such as when I was dragging, either on the child element or off of it.  And since you're using `<a>` tags, I would assume you want the same thing?  I would rather not defeat that flexibility.  And I'm not using event capturing to cause that behaviour, it's just the fact that the browser rightly detects a click on your element.

What I did was to add code to my underlying elements' mouseup handler to not take any action unless a certain amount of time had elapsed, but that was on elements that didn't have a default click action. You're dealing with elements that do have a default action, though, which is to follow the link.  

You could do something similar, like add a click event handler to those `<a>` elements, which calls `event.preventDefault()`, and also add a mouseup handler for those elements which programatically follows the link if enough time has elapsed.

Happy to hear your thoughts.

**Comment by swizzmagik** [comment]
Thanks for the response. I had considered that something like this might be required. I was thinking that if I tapped into the API for your library on my click handler I should be able to then detect if there is a drag happening or it has happened recently. I think that the solution works for me if you want to close this issue. Thanks for the prompt response.
