### ISSUE TITLE
Center object in the middle of the panzoom

### ISSUE THREAD

**Issue by no12345678** [KensingtonTech/ng2-panzoom#19]
Hey :) i need help with the ng2panzoom:
1) i'm trying to center the object i'm showing in the panzoom area. i tried using the pandelta with 50% but no luck. i'm showing a large organization tree and i want the root to be in the center so when i click my custom button to "reset", it will center it based on the root.
i would love for help on this/example of you centering an object in the panzoom area.
2) small problem i have when panning the object and zooming before it halts completely, the object is thrown aside completely and sometimes out of view and i need to reset the view- any way i could disable zooming when isPanning = true?

It would mean so much if you could help me with this.

**Comment by mdellanave** [comment]
I had the same problem and I soved with this 

`this.panZoomAPI.panDelta({ x: -((containerWidth / 2) - (imageWidth / 2)), y: 0 });`

**Comment by KensingtonTech** [comment]
@no12345678 I'm very sorry for the long delay in responding.  Version 10, just released, has added some new helper API methods.  I think the method `centerTopLeft()` would be apropos for your use case.

As for problem #2, if it is still an issue for you, please open a separate issue with information provided in the issue template.  A reduced test case or video demonstrating the problem is required.
