### ISSUE TITLE
a .pan() or .matrix() would be good.

### ISSUE THREAD

**Issue by runette** [KensingtonTech/ng2-panzoom#7]
There is no method for panning the view - equivalent to the .zoomIn() and .zoomOut(). It would be very good to have a .pan() function or even better a method that takes a CSS transformation matrix.

**Comment by KensingtonTech** [comment]
@runette thanks for the suggestion.  The next release will have a few new convenience methods for panning.

**Comment by KensingtonTech** [comment]
Four new panning API methods have been added in now-published 1.1.0.  Hopefully one of them will be useful for your needs.  I'll leave this open for a couple of days, in case you have any feedback.

FYI, I probably won't be adding a matrix method anytime soon but PR's are welcome.



panToPoint(point: Point, [duration: number]) - Will animate the view so that the centre point of the view is at the point parameter coordinates, relative to the original, unzoomed content width and height.

panDelta(delta: Point, [duration: number]) - Will pan the view left, right, up, or down, based on a number of pixels relative to the original, unzoomed content.

panDeltaPercent(deltaPercent: Point, [duration: number]) - Will pan the view up, down, left, or right, based on a percentage of the original, unzoomed content width and height.

panDeltaAbsolute(delta: Point, [duration: number]) - Will pan the view left, right, up, or down, based on a number of pixels. This method doesn't adjust for scale. I'm not sure why you'd want this, but it's provided just in case.

**Comment by runette** [comment]
Excellent - thanks
