### ISSUE TITLE
Configurable mousebutton

### ISSUE THREAD

**Issue by IschaStork** [KensingtonTech/ng2-panzoom#8]
It would be useful to be able to configure which of the mouse buttons (left, middle or right) is used for panning.

**Comment by KensingtonTech** [comment]
Hi @IschaStork, sorry for not getting back to you sooner.  I've implemented your request on a branch but it was slightly trickier than might be expected because of the default handlers for those events.  I've overridden the contextmenu (right click) and auxclick (middle) handlers, but...  

I've run into an issue with middle button drag on Chrome as it seems to have a bug that prevents the mousedrag event from firing after mousedown on middle button until it receives a left click (unless I've missed another default handler, which is possible), but frankly it's such an edge case that I'm not motivated to submit a bug report.  If it's critical for you, by all means feel free to do so.  It seems to work correctly on Firefox, though, so I imagine if/when that bug ever gets fixed, then it should start working on Chrome.

If you have any comments, I'm happy to hear them.  I will probably merge sometime in the next few days, otherwise.

**Comment by KensingtonTech** [comment]
@IschaStork this has been implemented in 2.1.0, now released.

**Comment by IschaStork** [comment]
Thanks for implementing this feature so quick, looking forward to using it.
